back/urls.py
from django.urls import path

from back.views import EventsListView, EventDetailView, UserCreateView, EventCreateView, UserQRCodeView, export_data, \
    web_hook_view, AnotherUserCreateView, AnotherUserQRCodeView

app_name = 'back'

urlpatterns = [
    # events
    path('events/list/', EventsListView.as_view(), name='events'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),

    # users
    path('', UserCreateView.as_view(), name='user-create'),
    path('another/', AnotherUserCreateView.as_view(), name='another-user-create'),
    path('user/<int:pk>/', UserQRCodeView.as_view(), name='user-detail'),
    path('another/user/<int:pk>/', AnotherUserQRCodeView.as_view(), name='another-user-detail'),

    # webhook and excel
    path('export/<int:pk>/', export_data, name='export-excel'),
    path('webhook/', web_hook_view, name='webhook'),
]

qr/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from qr import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('back.urls', namespace='back')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/another_registration.html
{% extends 'base.html' %}

{% block detail %}


    <div class="divCenter">
        <form action="" method="post" enctype="multipart/form-data" onsubmit="removeSpaces()">
            {% csrf_token %}
            <div class="register">
                <h2 class="eventName register_eventName">Registratsiya</h2>
                <div class="register__grid">
                    <div class="divInput">
                        <label class="label">Ism:
                            <input class="input" id="first_name" name="first_name" required type="text"
                                   placeholder="Ism">
                        </label>
                        <label class="label">Familiya:
                            <input class="input" id="last_name" name="last_name" required type="text"
                                   placeholder="Familiya">
                        </label>
                        <label class="label"> Telefon Raqam:
                            <input type="tel" class="input" id="phone_number" name="phone_number" value="+998 "
                                   placeholder="+998 (__) ___ __ __ __" maxlength="19"
                                   oninput="formatPhoneNumber(this)">

                        </label>
                        <label class="label">Ilmiy daraja:
                            <input class="input" id="academic_degree" name="academic_degree" type="text"
                                   placeholder="Akademik daraja">
                        </label>
                        <div class="divSelect">
                            <label class="label">Tadbirlar:
                                <select class="input" name="event" required>
                                    {% for event in events %}
                                        <option class="option" value="{{ event.id }}">{{ event.event_name }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="divButton register_divButton">
                    <a class="aLink" href="{% url 'back:another-user-create' %}">
                        <button type="button" class="button register_button__back">
                            Tozalash
                        </button>
                    </a>
                    <button type="submit" class="aLink button register_button__register">
                        Saqlash
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}


{% block extra_js %}
    <script>
        function formatPhoneNumber(input) {
            let phoneNumber = input.value.replace(/\D/g, '');
            let formattedNumber = '+998 ';

            if (phoneNumber.length > 3) {
                formattedNumber += '(' + phoneNumber.substring(3, 5);
            }

            if (phoneNumber.length >= 5) {
                formattedNumber += ') ' + phoneNumber.substring(5, 8);
            }

            if (phoneNumber.length >= 8) {
                formattedNumber += ' ' + phoneNumber.substring(8, 10);
            }

            if (phoneNumber.length >= 10) {
                formattedNumber += ' ' + phoneNumber.substring(10, 12);
            }

            if (phoneNumber.length >= 12) {
                formattedNumber += ' ' + phoneNumber.substring(12, 14);
            }

            input.value = formattedNumber;

            if (phoneNumber.length > 19) {
                input.value = input.value.substring(0, 19);
            }
        }
    </script>
{% endblock %}

templates/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TIIAME QR</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/tiiame_icon.png' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>

{% block detail %}{% endblock %}

<script src="{% static 'js/script.js' %}"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

templates/event_create.html
{% extends 'base.html' %}

{% block extra_css %}{% endblock %}

{% block detail %}

    <div class="divCenter">
        <div class="eventCreate">
            <h1 class="eventName">Tadbir yaratish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="divInput">
                    <label class="label">Tadbir nomi:
                        <input class="input" id="event_name" name="event_name" type="text" placeholder="Event-Name"
                               required>
                    </label>
                    <label class="label">Sana:
                        <input class="input" id="date" name="date" type="date" placeholder="Date" required>
                    </label>
                    <label class="label">Vaqt:
                        <input class="input" id="time" name="time" type="time" placeholder="Time" required>
                    </label>
                </div>

                <div class="divButton">
                    <a class="alink" href="{% url 'back:events' %}">
                        <button type="submit" class="button">
                            Yaratish
                        </button>
                    </a>
                    <a class="alink" href="{% url 'back:events' %}">
                        <button type="button" class="button">
                            Orqaga
                        </button>
                    </a>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

templates/event_detail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}{% endblock %}

{% block detail %}
    <div class="bgColor">
        <div class="container">
            <div class="studentsInfoGrid">
                <div class="studentsInfoHeader">
                    <h2 class="eventName studentsInfoHeader_eventName eventName__hidden eventName__width">
                        {{ object.event_name }}
                    </h2>
                    <a class="alink" href="{% url 'back:export-excel' pk=object.pk %}">
                        <button class="button studentsInfoHeader_button">
                            Yuklab olish
                        </button>
                    </a>
                </div>
                <div class="studentsInfoBody">
                    <div class="studentsInfoBar">
                        <div class="eventInfoBar">
                            <p class="p">{{ object.date }} soat {{ object.time|time:'H:i' }} da</p>
                        </div>
                        <div class="studentsBarTable">
                            <table class="table studentsBarTable_table">
                                <tr class="tr">
                                    <th class="th studentsInfoTable_th">Fakultet:</th>
                                    <th class="th studentsInfoTable_th">Soni:</th>
                                </tr>
                                {% for faculty, count in faculty_counts.items %}
                                    <tr class="tr">
                                        <td class="td studentsInfoTable_td td__left"> {{ faculty }}</td>
                                        <td class="td studentsInfoTable_td">{{ count }}</td>
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <td class="td studentsInfoTable_td studentsInfoTable_td__green1 td__left">Holis
                                        tinglovchilar:
                                    </td>
                                    <td class="td studentsInfoTable_td studentsInfoTable_td__green2">{{ object.another_users.count }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="divButton">
                            <a class="alink" href="{% url 'back:events' %}">
                                <button class="button">
                                    Orqaga
                                </button>
                            </a>
                        </div>
                    </div>
                    <div class="studentsInfoTable">
                        <div class="divStudents">
                            <div id="openDiv1" class="nameDiv">
                                <h2 class="h2 eventName studentsInfoTable_h1">Talaba Ma'lumoti</h2>
                                <img id="image1" class="arrow" src="{% static '/img/realArrow.png' %}" alt="img">
                            </div>
                            <div class="studentsInfo hidden" id="first_div">
                                <div style="min-height: 0">
                                    <table class="table studentsInfoTable_table">
                                        <tr class="tr studentsInfoTable_tr">
                                            <th class="th studentsInfoTable_th">Ism</th>
                                            <th class="th studentsInfoTable_th">Familiya</th>
                                            <th class="th studentsInfoTable_th">Fakultet</th>
                                            <th class="th studentsInfoTable_th">Guruh</th>
                                            <th class="th studentsInfoTable_th">Telefon Raqam</th>
                                        </tr>
                                        {% for user in users %}
                                            <tr class="tr studentsInfoTable_tr">
                                                <td class="td studentsInfoTable_td">{{ user.first_name }}</td>
                                                <td class="td studentsInfoTable_td">{{ user.last_name }}</td>
                                                <td class="td studentsInfoTable_td">{{ user.faculty.faculty_name }}</td>
                                                <td class="td studentsInfoTable_td">{{ user.group }}</td>
                                                <td class="td studentsInfoTable_td">
                                                    {% if user.phone_number|first == '+' %}
                                                        {% if user.phone_number|length|get_digit:'-1' < 10 %}
                                                            998{{ user.phone_number }}
                                                        {% else %}
                                                            {{ user.phone_number }}
                                                        {% endif %}
                                                    {% else %}
                                                        {% if user.phone_number|length|get_digit:'-1' < 10 %}
                                                            +998{{ user.phone_number }}
                                                        {% else %}
                                                            +{{ user.phone_number }}
                                                        {% endif %}
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="divListener">
                            <div id="openDiv2" class="nameDiv">
                                <h2 class="h2 eventName studentsInfoTable_h1">Holis tinglovchilar</h2>
                                <img id="image2" class="arrow" src="{% static '/img/realArrow.png' %}" alt="img">
                            </div>
                            <div class="ListenerInfo hidden" id="second_div">
                                <div style="min-height: 0">
                                    <table class="table studentsInfoTable_table">
                                        <tr class="tr studentsInfoTable_tr">
                                            <th class="th studentsInfoTable_th">Ilmiy daraja</th>
                                            <th class="th studentsInfoTable_th">Ism</th>
                                            <th class="th studentsInfoTable_th">Familiya</th>
                                            <th class="th studentsInfoTable_th">Telefon Raqam</th>
                                        </tr>
                                        {% for user in another_users %}
                                            <tr class="tr studentsInfoTable_tr">
                                                <td class="td studentsInfoTable_td">
                                                    {% if user.academic_degree %}
                                                        {{ user.academic_degree }}
                                                    {% endif %}

                                                </td>
                                                <td class="td studentsInfoTable_td">{{ user.first_name }}</td>
                                                <td class="td studentsInfoTable_td">{{ user.last_name }}</td>
                                                <td class="td studentsInfoTable_td">
                                                    {% if user.phone_number|first == '+' %}
                                                        {% if user.phone_number|length|get_digit:'-1' < 10 %}
                                                            998{{ user.phone_number }}
                                                        {% else %}
                                                            {{ user.phone_number }}
                                                        {% endif %}
                                                    {% else %}
                                                        {% if user.phone_number|length|get_digit:'-1' < 10 %}
                                                            +998{{ user.phone_number }}
                                                        {% else %}
                                                            +{{ user.phone_number }}
                                                        {% endif %}
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        const first_div = document.getElementById("first_div");
        let openDiv1 = document.getElementById("openDiv1");
        const second_div = document.getElementById("second_div");
        let openDiv2 = document.getElementById("openDiv2");
        const image1 = document.getElementById("image1");
        const image2 = document.getElementById("image2");

        let angle1 = 0;
        let angle2 = 0;

        openDiv1.addEventListener("click", () => {
            first_div.classList.toggle('hidden')
            first_div.classList.toggle('open')

            function rotateImage() {
                if (angle1 === 0) {
                    angle1 += 90;
                    image1.style.transform = `rotate(${angle1}deg)`;
                } else {
                    angle1 -= 90;
                    image1.style.transform = `rotate(${angle1}deg)`;
                }
            }

            rotateImage()
        })

        openDiv2.addEventListener("click", () => {
            second_div.classList.toggle('hidden')
            second_div.classList.toggle('open')

            function rotateImage() {
                if (angle2 === 0) {
                    angle2 += 90;
                    image2.style.transform = `rotate(${angle2}deg)`;
                } else {
                    angle2 -= 90;
                    image2.style.transform = `rotate(${angle2}deg)`;
                }
            }

            rotateImage()
        })
    </script>
{% endblock %}

templates/events.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}{% endblock %}

{% block detail %}
    <header class="header">
        <div class="container">
            <div class="eventHeader">
                <img src="{% static '/img/logo_1.png' %}" alt="Img-logo" class="eventHeader_img">
                <a href="{% url 'back:event-create' %}">
                    <button class="button eventHeader_button">Tadbir Yaratish</button>
                </a>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="eventGrid">
            {% for event in events %}
                <div class="eventInfo">
                    <div class="divEventInfo">
                        <h1 class="eventName eventName__width eventName__hidden">{{ event.event_name }}</h1>
                    </div>
                    <div class="divEventInfo divEventInfo__grid">
                        <p class="p">
                            Sana:<span class="number">{{ event.date|date:'d.m.Y' }}</span>
                        </p>
                        <p class="p">
                            Soat: <span><time
                                class="time">{{ event.time|time:'G:i' }}</time></span>
                        </p>
                        <p class="p">
                            Talabalar:
                            <span class="number">
                                {% if event.users %}{{ event.users.count }}{% else %}0{% endif %}
                            </span>
                        </p>
                        <p class="p">
                            Boshqa tinglovchilar:
                            <span class="number">
                                {% if event.another_users %}{{ event.another_users.count }}{% else %}0{% endif %}
                            </span>
                        </p>
                    </div>
                    <div class="divEventInfo">
                        <a class="alink" href="{% url 'back:event-detail' pk=event.pk %}">
                            <button class="button divEventInfo_button">Ma'lumot</button>
                        </a>
                    </div>
                </div>
            {% endfor %}
            <a href="{% url 'back:event-create' %}">
                <button class="button eventHeader_button__media">+</button>
            </a>
        </div>
    </div>
{% endblock %}

templates/qr_for_another_user.html
{% extends 'base.html' %}

{% block detail %}
    <div class="container">
        <div class="Media">
            <div class="studentsQr">
                <div class="divQr">
                    <img class="img divQr_img" src="{{ object.qr_code.url }}" alt="QR">
                </div>
                <div class="studentsInfoP">
                    <h1 class="eventName">
                        {{ object.event.event_name }}
                    </h1>
                    <p class="p">
                        Ism Familiya: {{ object.academic_degree }} {{ object.first_name }} {{ object.last_name }}
                    </p>
                    <p class="p">
                        Telefon Raqam:
                        {% if object.phone_number|stringformat:"s"|slice:"0:1" == "+" %}
                            {{ object.phone_number }}
                        {% else %}
                            +{{ object.phone_number }}
                        {% endif %}
                    </p>
                    <p class="p">
                        {{ object.event.date }} soat {{ object.event.time }} da
                    </p>
                </div>
                <div class="divButton">
                    <a class="alink" href="{{ object.qr_code.url }}" download="qrcode.png">
                        <button class="button studentsQr_button">
                            Yuklab olish
                        </button>
                    </a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/qr_for_user.html
{% extends 'base.html' %}

{% block detail %}
    <div class="container">
        <div class="Media">
            <div class="studentsQr">
                <div class="divQr">
                    <img class="img divQr_img" src="{{ object.qr_code.url }}" alt="QR">
                </div>
                <div class="studentsInfoP">
                    <h1 class="eventName">
                        {{ object.event.event_name }}
                    </h1>
                    <p class="p">
                        Talaba: {{ object.first_name }} {{ object.last_name }}
                    </p>
                    <p class="p">
                        Guruh: {{ object.group }}
                    </p>
                    <p class="p">
                        Fakultet: {{ object.faculty.faculty_name }}
                    </p>
                    <p class="p">
                        {{ object.event.date }} soat {{ object.event.time }} da
                    </p>
                </div>
                <div class="divButton">
                    <a class="alink" href="{{ object.qr_code.url }}" download="qrcode.png">
                        <button class="button studentsQr_button">
                            Yuklab olish
                        </button>
                    </a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block detail %}


    <div class="divCenter">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="register">
                <h2 class="eventName register_eventName">Registratsiya</h2>
                    <div class="register__grid">
                        <div class="divInput">
                            <label class="label"> Ism:
                                <input class="input" id="first_name" name="first_name" required type="text"
                                       placeholder="Ism">
                            </label>
                            <label class="label"> Familiya:
                                <input class="input" id="last_name" name="last_name" required type="text"
                                       placeholder="Familiya">
                            </label>
                            <label class="label"> Telefon Raqam:
                                <input type="tel" class="input" id="phone_number" name="phone_number" value="+998 "
                                       placeholder="+998 (__) ___ __ __" maxlength="19"
                                       oninput="formatPhoneNumber(this)">
                            </label>
                            <label class="label"> Guruh:
                                <input class="input" id="group" name="group" required type="text"
                                       placeholder="Guruh">
                            </label>
                        </div>
                        <div class="divSelect">
                            <label class="label">Fakultet:
                                <select class="input" id="faculty" name="faculty" required>
                                    {% for faculty in faculties %}
                                        <option class="option"
                                                value="{{ faculty.id }}">{{ faculty.faculty_name }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                            <label class="label">Tadbir:
                                <select class="input" name="event" required>
                                    {% for event in events %}
                                        <option class="option" value="{{ event.id }}">{{ event.event_name }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="divButton register_divButton">
                        <a class="aLink" href="{% url 'back:another-user-create' %}">
                            <button type="button" class="button register_button__back">
                                Holis Tinglovchi
                            </button>
                        </a>
                        <button type="submit" class="aLink button register_button__register">
                            Saqlash
                        </button>
                    </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        function formatPhoneNumber(input) {
            let phoneNumber = input.value.replace(/\D/g, '');
            let formattedNumber = '+998 ';

            if (phoneNumber.length > 3) {
                formattedNumber += '(' + phoneNumber.substring(3, 5);
            }

            if (phoneNumber.length >= 5) {
                formattedNumber += ') ' + phoneNumber.substring(5, 8);
            }

            if (phoneNumber.length >= 8) {
                formattedNumber += ' ' + phoneNumber.substring(8, 10);
            }

            if (phoneNumber.length >= 10) {
                formattedNumber += ' ' + phoneNumber.substring(10, 12);
            }

            if (phoneNumber.length >= 12) {
                formattedNumber += ' ' + phoneNumber.substring(12, 14);
            }

            input.value = formattedNumber;

            if (phoneNumber.length > 19) {
                input.value = input.value.substring(0, 19);
            }
        }
    </script>
{% endblock %}